# AMT default configuration file

provenance:
  datacapture:
    ### Image capture ###
    # The operating model, currently only "TimeLapse" is supported
    mode: TimeLapse

    # Whatevs
    hardware:
      # Computer running AMT software
      processor: Raspberry Pi Zero W
      # Camera in use as a human readable string
      camera: Raspberry Pi HQ + 6mm Wide Angle Lens
      # The operating distance of the camera from the illuminated surface, in mm
      operatingdistance: 265
      mothlight: High-power LED tube - 4 UV, 1 green, 1 blue
      illumination: 10-inch ring light
      sensortype: DHT22
      gpiogreen: 25
      gpiored: 7
      gpiolights: 26
      gpiosensorpower: 10
      gpiosensordata: 9
      gpiomanual: 22
      gpiotransfer: 27
      gpioshutdown: 17
      gpiotrigger: 16

    # Canera settings
    camerasettings:
      folder: /home/pi/AMT/
      imagewidth: 4056
      imageheight: 3040
      brightness: 62
      contrast: 30
      saturation: 20
      sharpness: 50
      quality: 20
      awb_mode: off
      awb_gains: 
      - 2.8
      - 1.6